
export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg,#e6f8f3 0%,#f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg,#fef9e7 0%,#fffdf4 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg,#eaf7ff 0%,#f3fbff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg,#fff2e9 0%,#fff8f3 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg,#e7f6fe 0%,#f4fafd 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg,#f5f5f5 0%,#fbfbfb 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg,#fff4fc 0%,#fff8fd 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg,#e8fef3 0%,#f5fef8 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg,#f0ecff 0%,#f5fef8 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg,#fef2f2 0%,#fff8f8 100%)' },
];




export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just For You",
    description: "Get interview questions and model answers based on role, experience, and specific focus areas—no generic practice here.",
    titleColor: "#FF6F00",       // Deep orange
    descriptionColor: "#5D4037", // Dark brownish gray
  },
  {
    id: "02",
    title: "Learn At Your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
    titleColor: "#1E88E5",       // Bright blue
    descriptionColor: "#424242", // Dark gray
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description: "Add personal notes to any question and pin important ones to the top—making your learning more organized and impactful.",
    titleColor: "#FB8C00",       // Vivid orange
    descriptionColor: "#616161", // Medium gray
  },
  {
    id: "04",
    title: "Understand the 'why' Behind Answers",
    description: "Beyond just answers—unlock detailed concept explanations generated by AI, helping you truly master each topic.",
    titleColor: "#1976D2",       // Strong blue
    descriptionColor: "#757575", // Gray
  },
  {
    id: "05",
    title: "Save, Organize and Revisit",
    description: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
    titleColor: "#EF6C00",       // Orange
    descriptionColor: "#9E9E9E", // Light gray
  },
];
